# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            ExplEnglish
tagline:          "The English teacher's library"
description:      'ExplEnglish is a library of English lessons, drills, and reference material for teachers and learners.'
url:              https://explenglish.com
baseurl:          /

author:
  name:           'ExplEnglish'

paginate:         5
